# Generated by Django 5.1.4 on 2025-02-09 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_properties_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_image', models.ImageField(blank=True, null=True, upload_to='images/properties/')),
                ('user_property', models.ForeignKey(help_text='Add images of your property', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.properties')),
            ],
        ),
    ]
