# Generated by Django 5.1.4 on 2025-02-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimages',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
