import type { Metadata } from "next";
import { manRope } from "../utilities/font";
import "./globals.css";
import Navbar from "./ui/navbar";
import Footer from "./ui/footer";
import ReduxProvider from "../store/provider";

import ModalProvider from "../context/context";
import Modals from "../components/modals/modals";
import NextQueryProvider from "./queryclient";

import { ToastContainer } from "react-toastify";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

export const metadata: Metadata = {
  title: {
    template: "%s | Airbnb",
    default: "Vacation Rentals, Cabins, Beach",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={`${manRope.className} text-black antialiased`}>
        <ModalProvider>
          <NextQueryProvider>
            <ReduxProvider>
              {/* Wrap everything in a container */}
              <div className="max-w-[150rem] mx-auto px-6">
                <Navbar />
                {children}
                <Footer />
              </div>

              {/* Modals, Toast, and DevTools outside max width */}
              <Modals />
              <ToastContainer />
              <ReactQueryDevtools />
            </ReduxProvider>
          </NextQueryProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
