# Generated by Django 5.1.4 on 2025-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_bankingdetails_account_number_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/'),
        ),
    ]
