export const locations = [
  {
    imageSrc: "/searchbar-image/img1.png",
    width: 50,
    height: 100,
    alt: "London",
    city: "London",
    country: "United Kingdom",
    description: "For sights like Buckingham Palace",
  },
  {
    imageSrc: "/searchbar-image/img2.png",
    width: 50,
    height: 0,
    alt: "Lekki",
    city: "Lekki",
    country: "Nigeria",
    description: "For its seaside allure",
  },
  {
    imageSrc: "/searchbar-image/img3.png",
    width: 50,
    height: 100,
    alt: "Picture of the author",
    city: "Toronto",
    country: "Canada",
    description: "For its bustling nightlife",
  },
  {
    imageSrc: "/searchbar-image/img4.png",
    width: 50,
    height: 100,
    alt: "Picture of the author",
    city: "Mississauga",
    country: "Canada",
    description: "For a trip abroad",
  },
  {
    imageSrc: "/searchbar-image/img5.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Ikeja",
    country: "Nigeria",
    description: "Near You",
  },
  {
    imageSrc: "/searchbar-image/img6.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Accra",
    country: "Ghana",
    description: "Popular beach destination",
  },
  {
    imageSrc: "/searchbar-image/img7.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Abuja",
    country: "Nigeria",
    description: "For a trip abroad",
  },
  {
    imageSrc: "/searchbar-image/img8.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Winnipeg",
    country: "Canada",
    description: "For a trip abroad",
  },
  {
    imageSrc: "/searchbar-image/img9.png",
    width: 50,
    height: 100,
    alt: "Picture of the author",
    city: "Brimingham",
    country: "United Kingdom",
    description: "For a trip abroad",
  },
  {
    imageSrc: "/searchbar-image/img10.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Paris",
    country: "France",
    description: "For sights like Effiel Tower",
  },
  {
    imageSrc: "/searchbar-image/img11.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Nairobi",
    country: "Kenya",
    description: "For nature lovers",
  },
  {
    imageSrc: "/searchbar-image/img12.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Manchester",
    country: "United Kingdom",
    description: "For its bustling nightlife",
  },
  {
    imageSrc: "/searchbar-image/img13.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Brampton",
    country: "Canada",
    description: "For a trip abroad",
  },
  {
    imageSrc: "/searchbar-image/img14.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Calgary",
    country: "Canada",
    description: "Known for its skiing",
  },
  {
    imageSrc: "/searchbar-image/img15.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Edmonton",
    country: "Canada",
    description: "For sights like west Edmonton Mall",
  },
  {
    imageSrc: "/searchbar-image/img16.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Ottawa",
    country: "Canada",
    description: "For a trip abroad",
  },
  {
    imageSrc: "/searchbar-image/img17.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Salford",
    country: "United Kingdom",
    description: "A hidden gem",
  },
  {
    imageSrc: "/searchbar-image/img18.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Halifax",
    country: "Canada",
    description: "For a trip abroad",
  },
  {
    imageSrc: "/searchbar-image/img19.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Hamilton",
    country: "Canada",
    description: "For a trip abroad",
  },
  {
    imageSrc: "/searchbar-image/img20.png",
    width: 60,
    height: 100,
    alt: "Picture of the author",
    city: "Regina",
    country: "Canada",
    description: "For a trip abroad",
  },
];
